
CREATE TABLE PLAYLISTINFO(
    author NCHAR(32) NOT NULL,
    name NVARCHAR(255) PRIMARY KEY NOT NULL,
    description NVARCHAR(255)
);
CREATE TABLE COLLECTION(
    playlist NVARCHAR(255) NOT NULL,
    title NVARCHAR(255) NOT NULL,
    artist NVARCHAR(32) NOT NULL,
    album NVARCHAR(32) NOT NULL,
    pubyear INTEGER NOT NULL,
    url NVARCHAR(255) NOT NULL,
    duration INTEGER NOT NULL,
    weight INTEGER DEFAULT 1
);
CREATE TABLE CACHE(
    title NVARCHAR(255) NOT NULL,
    artist NVARCHAR(32) NOT NULL,
    album NVARCHAR(32) NOT NULL,
    pubyear INTEGER NOT NULL,
    url NVARCHAR(255) PRIMARY KEY NOT NULL,
    duration INTEGER NOT NULL,
    cover BOLB
)